export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_CITY_DATA = "GET_CITY_DATA";
export const GET_SUPPORTED_COUNTRIES = "GET_SUPPORTED_COUNTRIES";
export const GET_SUPPORTED_STATES = "GET_SUPPORTED_STATES";
export const GET_SUPPORTED_CITIES = "GET_SUPPORTED_CITIES";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
